### PR TITLE
rm types from nested data structures

### PR DESCRIPTION
**Pull request by kablamo**
Net::Amazon::DynamoDB::Lite removes types from item returned by the Amazon API.  This pr adds the ability to handle items with nested data like this:

```
my $item = { 
    node      => $node,
    flavor    => 'flavor',
    thing     => [
        {
            a => 'firstthing1',
            b => 2001,  
            c => 201,
        }, {
            a => 'firstthing2',
            b => 2002,  
            c => 202,
        }

    ], 
};
```

### CODE REVIEW

**Comment by kablamo** [comment]
Added a test for this fix

**Comment by kablamo** [comment]
Hi!  I can't use this module until this pr is merged.  Let me know if there is anything I can do to help.  Or if I can somehow make this easier for you to merge.

**Comment by ka2u** [comment]
I'm sorry that to check it is delayed. It'll be check, so please wait a moment a little more. Thank you.

**Comment by kablamo** [comment]
yay \o/  :balloon:

**Pull request merged**
